source 'https://github.com/CocoaPods/Specs.git'


platform:ios,'9.0'
use_frameworks!
# ignore all warnings from all pods
inhibit_all_warnings!

def pods	
    pod 'RxSwift',    '~> 4.0'
    pod 'RxCocoa',    '~> 4.0'
    pod 'RxBlocking', '~> 4.0'
    pod 'RxTest',     '~> 4.0'
end

target 'RXSwiftStudy' do
    pods
end


post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'YES'
            config.build_settings['SWIFT_VERSION'] = '4.2'
        end
    end
end
