//: [Previous](@previous)

import Foundation

func getFirstCharacter(_ s:String) -> Int {
    
    var character = [Character]()
    
    for char in s {
        character.append(char)
    }
    
    var dic = [Character:Int]()
    
    for i in 0..<s.count {
        let cur = dic[character[i]] ?? 0
        dic[character[i]]  = cur + 1
    }
    
    for i in 0..<s.count {
        if dic[character[i]] == 1 {
            return i
        }
    }
    
    return -1
}



let result = getFirstCharacter("Aerbu0")


let dogString = "a"
for scalar in dogString.unicodeScalars {
    print("\(scalar.value) ", terminator: "")
}
print("")
// Prints "68 111 103 8252 128054 "

for scalar in dogString.unicodeScalars {
    print("\(scalar) ")
}


func firstUniqChar(_ s: String) -> Int {
    
    var arr = [Int]()

    for _ in 0..<26 {
        arr.append(0)
    }

    for scalar in s.unicodeScalars {
        let index = Int(scalar.value - 97)
        let cur = arr[index]
        arr[index] = cur + 1
    }

    var first = 0
    
    for scalar in s.unicodeScalars {
        let index = Int(scalar.value - 97)
        if arr[index] == 1 {
            return first
        }
        first += 1
    }
    
    return -1
}




let a = firstUniqChar("edihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdujddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihpdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdljddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiqedihdjddwfjihwefihewiq")
